import fs from "node:fs";
import path from "node:path";

export interface ArticleItem {
  url: string;
  title: string;
  summary: string;
}

export function parseArticles(): void {
  const inputFilePath = path.resolve("data", "articles.dpod.txt");
  const outputDir = path.resolve("js", "data");
  const outputFilePath = path.join(outputDir, "articles.js");

  if (!fs.existsSync(inputFilePath)) {
    console.warn(`[parse-articles] Input file not found: ${inputFilePath}`);
    return;
  }

  const fileContent = fs.readFileSync(inputFilePath, "utf-8");
  const lines = fileContent.split(/\r?\n/);

  const articles: ArticleItem[] = [];

  for (const line of lines) {
    const trimmedLine = line.trim();
    if (!trimmedLine || trimmedLine.startsWith("#")) {
      continue;
    }

    const parts = trimmedLine.split(";");
    if (parts.length >= 2) {
      const url = parts[0].trim();
      const title = parts[1].trim();
      const summary = parts.slice(2).join(";").trim();

      if (url && title) {
        articles.push({ url, title, summary });
      }
    }
  }

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const jsContent = `// Auto-generated by cmd/parse-data.ts - DO NOT EDIT MANUALLY\nexport const articles = ${JSON.stringify(
    articles,
    null,
    2
  )};\n`;

  fs.writeFileSync(outputFilePath, jsContent, "utf-8");
  console.log(`[parse-articles] Parsed ${articles.length} articles -> ${outputFilePath}`);
}
