import fs from "node:fs";
import path from "node:path";

export interface ConceptItem {
  whenAdded: string;
  id: string;
  title: string;
  summary: string;
}

export function parseConcepts(): void {
  const inputFilePath = path.resolve("data", "concepts.dpod.txt");
  const outputDir = path.resolve("js", "data");
  const outputFilePath = path.join(outputDir, "concepts.js");

  if (!fs.existsSync(inputFilePath)) {
    console.warn(`[parse-concepts] Input file not found: ${inputFilePath}`);
    return;
  }

  const fileContent = fs.readFileSync(inputFilePath, "utf-8");
  const lines = fileContent.split(/\r?\n/);

  const concepts: ConceptItem[] = [];

  for (const line of lines) {
    const trimmedLine = line.trim();
    if (!trimmedLine || trimmedLine.startsWith("#")) {
      continue;
    }

    const parts = trimmedLine.split(";");
    if (parts.length >= 4) {
      // Format: whenAdded; id; title; summary
      const whenAdded = parts[0].trim();
      const id = parts[1].trim();
      const title = parts[2].trim();
      const summary = parts.slice(3).join(";").trim();

      if (id && title) {
        concepts.push({ whenAdded, id, title, summary });
      }
    } else if (parts.length === 3) {
      // Fallback format without whenAdded: id; title; summary
      const id = parts[0].trim();
      const title = parts[1].trim();
      const summary = parts.slice(2).join(";").trim();

      if (id && title) {
        concepts.push({ whenAdded: "", id, title, summary });
      }
    }
  }

  // Sort concepts newest to oldest by whenAdded timestamp
  concepts.sort((a, b) => {
    if (!a.whenAdded) return 1;
    if (!b.whenAdded) return -1;
    return b.whenAdded.localeCompare(a.whenAdded);
  });

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const jsContent = `// Auto-generated by cmd/parse-data.ts - DO NOT EDIT MANUALLY\nexport const concepts = ${JSON.stringify(
    concepts,
    null,
    2
  )};\n`;

  fs.writeFileSync(outputFilePath, jsContent, "utf-8");
  console.log(`[parse-concepts] Parsed ${concepts.length} concepts -> ${outputFilePath}`);
}
